from .dashboard_view import *
from .home_view import *
from .log_in_view import *
from .log_out_view import *
from .password_view import *
from .profile_view import *
from .settings_view import *
from .recipes_view import *
from .sign_up_view import *
from .tracker_view import *
from .water_history_view import *
from .nutrition_history_view import *
from .fasting_history_view import *
from .welcome_view import *
from .social_feed import *
from .add_meal_view import *
from .ai_recipe import chatbot
from .my_recipes_view import *
from .add_recipe_view import *
from .recipe_detail_view import *
from .edit_recipe_view import *
