# Generated by Django 5.2.7 on 2025-11-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('average_rating', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard')], max_length=20)),
                ('total_time', models.CharField(max_length=50)),
                ('servings', models.PositiveIntegerField(default=1)),
                ('ingredients', models.TextField()),
                ('method', models.TextField()),
            ],
        ),
    ]
