# Generated by Django 5.2.7 on 2025-11-30 07:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_fastingsession_meal_profile_waterintake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_weight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='fasting_goal',
            field=models.IntegerField(choices=[(12, '12 hours'), (14, '14 hours'), (16, '16 hours'), (18, '18 hours'), (20, '20 hours')], default=16),
        ),
        migrations.AlterField(
            model_name='fastingsession',
            name='target_duration',
            field=models.IntegerField(choices=[(14, '14 hours'), (16, '16 hours'), (18, '18 hours')], default=16),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='profile',
            name='carbs_goal',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fat_goal',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='profile',
            name='protein_goal',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
