# Generated by Django 5.2.7 on 2025-11-30 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe'),
        ('recipes', '0003_rename_content_comment_text_and_more'),
    ]

    operations = [
    ]
