# Generated by Django 5.2.7 on 2025-12-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(default=0, help_text='Calories per serving'),
        ),
    ]
