# Generated by Django 5.2.7 on 2025-11-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_profile_current_weight_remove_profile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fasting_goal',
            field=models.IntegerField(choices=[(12, '12 hours'), (14, '14 hours'), (16, '16 hours'), (18, '18 hours')], default=16),
        ),
    ]
