# Generated by Django 5.2.7 on 2025-11-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_fastingsession_meal_profile_waterintake'),
        ('recipes', '0004_merge_20251130_0329'),
    ]

    operations = [
    ]
