# Generated by Django 5.2.7 on 2025-11-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_profile_fasting_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastingsession',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
