# Generated by Django 5.2.7 on 2025-12-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_content_comment_text_and_more'),
        ('recipes', '0006_fastingsession_end_date_time'),
    ]

    operations = [
    ]
