# Generated by Django 5.2.7 on 2025-11-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_merge_20251130_1320'),
        ('recipes', '0006_fastingsession_end_date_time'),
    ]

    operations = [
    ]
