# Generated by Django 5.2.7 on 2025-12-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_merge_20251130_1337'),
        ('recipes', '0007_merge_20251205_1503'),
    ]

    operations = [
    ]
