# Generated by Django 5.2.7 on 2025-12-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_merge_20251130_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterField(
            model_name='fastingsession',
            name='target_duration',
            field=models.IntegerField(choices=[(14, '14 hours'), (16, '16 hours'), (18, '18 hours'), (20, '20 hours')], default=16),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
