# Generated by Django 5.2.7 on 2025-12-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_merge_20251130_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastingsession',
            name='target_duration',
            field=models.IntegerField(choices=[(14, '14 hours'), (16, '16 hours'), (18, '18 hours'), (20, '20 hours')], default=16),
        ),
    ]
