# Generated by Django 5.2.7 on 2025-12-05 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_fastingsession_target_duration'),
    ]

    operations = [
    ]
