# Generated by Django 5.2.7 on 2025-12-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_merge_20251130_1337'),
        ('recipes', '0009_dailylog_delete_waterintake'),
        ('recipes', '0009_post_image_post_rating_count_post_rating_total_score_and_more'),
    ]

    operations = [
    ]
