# Generated by Django 5.2.7 on 2025-12-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_merge_20251207_2030'),
        ('recipes', '0010_merge_20251207_2148'),
    ]

    operations = [
    ]
