# Generated by Django 5.2.7 on 2025-12-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_merge_20251207_1532'),
        ('recipes', '0009_post_image_post_rating_count_post_rating_total_score_and_more'),
        ('recipes', '0010_dailylog_delete_waterintake'),
    ]

    operations = [
    ]
