# Generated by Django 5.2.7 on 2025-12-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_dailylog_delete_waterintake'),
        ('recipes', '0011_merge_20251207_1534'),
    ]

    operations = [
    ]
