# Generated by Django 5.2.7 on 2025-12-09 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_user_bio_user_dietary_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color_blind_mode',
            field=models.CharField(choices=[('none', 'None'), ('protanopia', 'Protanopia'), ('deuteranopia', 'Deuteranopia'), ('tritanopia', 'Tritanopia'), ('achromatopsia', 'Achromatopsia')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='font_scale',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.8), django.core.validators.MaxValueValidator(1.5)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='reduce_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
