# Generated by Django 5.2.7 on 2025-12-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_merge_20251207_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prep_time',
            field=models.CharField(blank=True, help_text='e.g. 25 min', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='servings',
            field=models.CharField(blank=True, help_text='e.g. 4 servings', max_length=50),
        ),
    ]
