# Generated by Django 5.2.7 on 2025-12-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_merge_20251207_2241'),
        ('recipes', '0013_post_prep_time_post_servings_delete_waterintake'),
    ]

    operations = [
    ]
