# Generated by Django 5.2.7 on 2025-12-10 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_profile_color_blind_mode_profile_font_scale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reduce_motion',
        ),
    ]
