# Generated by Django 5.2.7 on 2025-12-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_remove_profile_reduce_motion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_follower_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_weekly_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_profile_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reminder_log_meals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_stats_publicly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='units_preference',
            field=models.CharField(choices=[('metric', 'Metric (kg, ml)'), ('imperial', 'Imperial (lbs, oz)')], default='metric', max_length=10),
        ),
    ]
