# Generated by Django 5.2.7 on 2025-12-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_merge_20251208_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='prep_time',
            field=models.CharField(blank=True, help_text='e.g. 25 min', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='servings',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
