# Generated by Django 5.2.7 on 2025-12-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_post_difficulty_alter_post_prep_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Japanese', 'Japanese'), ('Thai', 'Thai'), ('French', 'French'), ('American', 'American'), ('Greek', 'Greek'), ('Spanish', 'Spanish'), ('Mediterranean', 'Mediterranean'), ('Korean', 'Korean'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
