# Generated by Django 5.2.7 on 2025-12-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_post_cuisine_delete_waterintake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterIntake',
        ),
    ]
