# Generated by Django 5.2.7 on 2025-12-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_post_cuisine_delete_waterintake'),
    ]

    operations = [
    ]
