# Generated by Django 5.2.7 on 2025-12-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_merge_20251207_2030'),
        ('recipes', '0010_merge_20251207_2148'),
        ('recipes', '0017_delete_waterintake'),
    ]

    operations = [
    ]
