# Generated by Django 5.2.7 on 2025-12-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_calories'),
        ('recipes', '0018_add_personal_rating_to_recipe'),
    ]

    operations = [
    ]
