# Generated by Django 5.2.7 on 2025-12-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_merge_20251130_2346'),
        ('recipes', '0009_recipe_image_url'),
        ('recipes', '0015_profile_email_follower_notifications_and_more'),
        ('recipes', '0019_comment_like'),
    ]

    operations = [
    ]
